### PR TITLE
Update to meet current HQRM guidelines - Fixes #11

### LINKED ISSUE #11: Update to use Shared AppVeyor module

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR changes:

* Added resource helper module.
* Change examples to meet HQRM standards and optin to Example validation
  tests.
* Replaced examples in README.MD to links to Example files.
* Added the VS Code PowerShell extension formatting settings that cause PowerShell
  files to be formatted as per the DSC Resource kit style guidelines.
* Opted into Common Tests 'Validate Module Files' and 'Validate Script Files'.
* Converted files with UTF8 with BOM over to UTF8.
* Updated Year to 2017 in License and Manifest.
* Added .github support files:
  * CONTRIBUTING.md
  * ISSUE_TEMPLATE.md
  * PULL_REQUEST_TEMPLATE.md
* Resolved all PSScriptAnalyzer warnings and style guide warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/systemlocaledsc/12)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @Johlju - I hate to be a pain, but would you at all mind reviewing this one - only when you get time- no rush!

**Comment by johlju** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[README.md, line 49 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyjor7eb5zZb7wiuAI7:-Kyjor7eb5zZb7wiuAI8:b-r64u0a) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/README.md#L49)):*
> SystemLocaleDsc

Should just be 'SystemLocale'?

---

*[.github/ISSUE_TEMPLATE.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyjp7i1IBZ1q0Wvikx9:-Kyjp7i1IBZ1q0WvikxA:bbswu0g) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/.github/ISSUE_TEMPLATE.md#L4)):*
> SystemLocaleDsc

Maybe just 'SystemLocale'? 

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpD-sxdEJEikPfPic:-KyjpD-sxdEJEikPfPid:b-uod9ad) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
> SystemLocaleDsc

Maybe just 'SystemLocale'? Here and the row below.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpeoRrx5USy71mSTx:-KyjpeoRrx5USy71mSTy:bkctzrn) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L1)):*
> ```PowerShell
> [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Scope = 'Function')]
> ```

Suggest moving this down to the `Set-TargetResource' (above `[CmdletBinding()]`.
Also, please add a comment.
```
# Suppressing this rule because $global:DSCMachineStatus is used to trigger a reboot.
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Scope = 'Function')]
[CmdletBinding()]
```

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 31 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpXPC-rxAdHqWpwN2:-KyjpXPC-rxAdHqWpwN3:bwrmcxs) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L31)):*
> [Hashtable]

Maybe we should add full namespace on this one as well. 

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 188 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjsOnNx--k3ply7a8D:-KyjsOnNx--k3ply7a8E:b-33k6jy) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L188)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory = $true)]
>         [System.String] $SystemLocale
> ```

Parameter variable name should be on the next row. 

---

*[Tests/Integration/MSFT_SystemLocale.Integration.Tests.ps1, line 70 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyju18aB1MfsTgZ80RC:-Kyju18aB1MfsTgZ80RD:bbrnryk) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/Tests/Integration/MSFT_SystemLocale.Integration.Tests.ps1#L70)):*
> ```PowerShell
>             }
>             # A reboot would need to occur before this node can be bought into alignment
>             $current.IsSingleInstance | Should Be $configData.AllNodes[0].IsSingleInstance
> ```

Should it not check the property `SystemLocale` here as well? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12)*

**Comment by PlagueHO** [comment]
All done. Thanks @johlju !

---

Review status: 13 of 19 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[README.md, line 49 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyjor7eb5zZb7wiuAI7:-Kz7txqxLdzOlTSKM9W-:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/README.md#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> SystemLocaleDsc

Should just be 'SystemLocale'?
</blockquote></details>

Done.

---

*[.github/ISSUE_TEMPLATE.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyjp7i1IBZ1q0Wvikx9:-Kz7u2YaJsLDbcJzOlcy:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/.github/ISSUE_TEMPLATE.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> SystemLocaleDsc

Maybe just 'SystemLocale'? 
</blockquote></details>

Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpD-sxdEJEikPfPic:-Kz7u7hk8UlKq6P6kXjL:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> SystemLocaleDsc

Maybe just 'SystemLocale'? Here and the row below.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpeoRrx5USy71mSTx:-Kz7uNoPOtIb8-wRFD6y:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest moving this down to the `Set-TargetResource' (above `[CmdletBinding()]`.
Also, please add a comment.
```
# Suppressing this rule because $global:DSCMachineStatus is used to trigger a reboot.
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Scope = 'Function')]
[CmdletBinding()]
```


</blockquote></details>

Done.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 31 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpXPC-rxAdHqWpwN2:-Kz7uYSAbGslh-mFiaBo:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L31)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> [Hashtable]

Maybe we should add full namespace on this one as well. 
</blockquote></details>

Done.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 188 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjsOnNx--k3ply7a8D:-Kz7ubSdSy4JMzMpN3In:b-896fix) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L188)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Parameter variable name should be on the next row. 
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SystemLocale.Integration.Tests.ps1, line 70 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-Kyju18aB1MfsTgZ80RC:-Kz7vmCBRCJ95TBPe-LP:bau8j02) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/Tests/Integration/MSFT_SystemLocale.Integration.Tests.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should it not check the property `SystemLocale` here as well? 
</blockquote></details>

Unfortunately I can't effectively test this here because a reboot needs to occur before the new System Locale is reported - which can't be done. I've improved the comment above to make this clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-:-Kz7zAQHk-wi8r_-w9iD:b-poqazu)*

**Comment by johlju** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpeoRrx5USy71mSTx:-Kz9k_rjJoNlRGfmyyJo:buolldk) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You did not remove the four rows at the top, are they still necessary after the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12)*

**Comment by PlagueHO** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KyjpeoRrx5USy71mSTx:-KzAuNXPky2uGtJYtB-2:bphurgd) ([raw file](https://github.com/powershell/systemlocaledsc/blob/1bdc1f405a3600edb9b147eb377e002ed836dba0/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You did not remove the four rows at the top, are they still necessary after the change?
</blockquote></details>

Ah wait! That's right - I forgot - this particular rule only seems to be able to be suppressed when applied at the script scope (regardless of the scope in the attribute). Here is the result:
https://ci.appveyor.com/project/PlagueHO/systemlocaledsc/build/1.1.13.0#L165

So I've improved the comments and moved this back to the top :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12)*

**Comment by johlju** [comment]
:lgtm:


I have it in the function here. But good as-is too, so this PR looks good to me know.
See here for reference: https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L642

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-:-KzF4pZA98RFDJrKZ0Sp:b-1ifhzv)*

**Comment by johlju** [comment]
This is not a comment around this PR, I'm just thinking loud here about the rule in xSQLServerSetup... Maybe since the rule applies to script scope maybe it should be at the top in xSQLServerSetup resource as well. I thought by putting it in the function, it only applies to the function regardless of scope. But haven't tested it. 🤔

**Comment by PlagueHO** [comment]
@Johlju - I see what I did wrong - I had specifically scoped it to the function - which doesn't work. So I've copied your one and it works fine :grin: can you mark it off if you're OK with it?

---

Review status: 18 of 19 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-:-KzNLw9Z2HyrFibWfHdi:b83yoh2)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 69 at r4](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KzOMlVP8W-ebpKay-B1:-KzOMlVP8W-ebpKay-B2:bh5c85w) ([raw file](https://github.com/powershell/systemlocaledsc/blob/718da749a8a9feea3fb37d0b27595a2d8d190744/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L69)):*
> "...either by force or when there are pending changes."

Actually this text is because in xSQLServerSetup we have a code logic for this, a ForceRestart parameter, and it checks if there are pending changes that needs restart.
In your case you always restart on change, the text should maybe say that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12)*

**Comment by PlagueHO** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1, line 69 at r4](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-KzOMlVP8W-ebpKay-B1:-KzSSkl6DwlrbWxpxivI:b-377tzk) ([raw file](https://github.com/powershell/systemlocaledsc/blob/718da749a8a9feea3fb37d0b27595a2d8d190744/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1#L69)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> "...either by force or when there are pending changes."

Actually this text is because in xSQLServerSetup we have a code logic for this, a ForceRestart parameter, and it checks if there are pending changes that needs restart.
In your case you always restart on change, the text should maybe say that?
</blockquote></details>

Good call - I totally missed this! Fixes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/systemlocaledsc/12#-:-KzUbR7yIhv91fd9rxhq:bnfp4nl)*

**Pull request merged**
