### PR TITLE
Deprecate resource - Fixes #14

### LINKED ISSUE #14: Combine SystemLocaleDsc Resource with ComputerManagementDsc
As we are converting xComputerManagement over to ComputerManagementDsc in the near future I thought it might be worth considering moving SystemLocaleDsc into ComputerManagementDsc at the same time. There has been some discussion around this in the past - see https://github.com/PowerShell/xComputerManagement/issues/50

@kwirkykat - do you have any thoughts on this? I'm happy to keep them separate but I thought it might simplify things as these "individual" resources make more sense together.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR deprecates the resource as it has been migrated into ComputerManagementDsc.

#### This Pull Request (PR) fixes the following issues

- Fixes #14

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - once [this PR](https://github.com/PowerShell/ComputerManagementDsc/pull/280) is through can you review this one? Should be pretty quick :grin:

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/systemlocaledsc/21)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/systemlocaledsc/21#-:-LsgVEHx77GDe5v0cf9e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
I'm ignoring CI fails since this module is being deprecated.

Should be merged after PR https://github.com/PowerShell/ComputerManagementDsc/pull/280 is merged.

We should also update the repo description like other deprecated modules, e.g https://github.com/PowerShell/xPowerShellExecutionPolicy.

**Comment by PlagueHO** [comment]
Thanks @johlju - I'm going to merge this one when ComputerManagementDsc is released next.

**Comment by PlagueHO** [comment]
I totally forgot about this one!

**Comment by PlagueHO** [comment]
Hi @gaelcolas - do you have permission to merge this one?

**Pull request merged**
